name: CD - Deploy to Rancher Desktop

on:
  workflow_run:
    workflows: ["CI - Build and Push Images"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: .

    - name: Debug directory structure
      run: |
        echo "Contenido de mywork:"
        ls -l /mnt/c/Users/jose.i.marin.ghalem/actions-runner/mywork
        echo "Contenido de mywork/training-devops-selfhosted:"
        ls -l /mnt/c/Users/jose.i.marin.ghalem/actions-runner/mywork/training-devops-selfhosted
        echo "Contenido de mywork/training-devops-selfhosted/k8s:"
        ls -l /mnt/c/Users/jose.i.marin.ghalem/actions-runner/mywork/training-devops-selfhosted/k8s || echo "k8s no existe"

    - name: Verify cluster connection
      run: |
        kubectl config current-context
        kubectl get nodes

    - name: Deploy Angular
      run: |
        kubectl apply -f /mnt/c/Users/jose.i.marin.ghalem/actions-runner/mywork/training-devops-selfhosted/k8s/angular-deployment.yaml

    - name: Deploy Spring Boot
      run: |
        kubectl apply -f /mnt/c/Users/jose.i.marin.ghalem/actions-runner/mywork/training-devops-selfhosted/k8s/springboot-deployment.yaml

    - name: Wait for pods to be ready
      run: |
        kubectl wait --for=condition=ready pod -l app=angular --timeout=120s
        kubectl wait --for=condition=ready pod -l app=springboot --timeout=120s

    - name: Verify services
      run: |
        kubectl get services
        curl --fail --silent http://localhost:30080 || echo "Angular service not accessible"
        curl --fail --silent http://localhost:30081/hello || echo "Spring Boot service not accessible"