name: CI - Build and Push Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # Paso 2: Inspeccionar la estructura del directorio
    - name: Debug directory structure
      run: |
        echo "Contenido de _work:"
        ls -l /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work
        echo "Contenido de _work/training-devops-selfhosted:"
        ls -l /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work/training-devops-selfhosted
        echo "Contenido de _work/training-devops-selfhosted/training-devops-selfhosted:"
        ls -l /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work/training-devops-selfhosted/training-devops-selfhosted
        echo "Contenido de _work/training-devops-selfhosted/training-devops-selfhosted/training-angular:"
        ls -l /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work/training-devops-selfhosted/training-devops-selfhosted/training-angular || echo "training-angular no existe"

    # Paso 3: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Paso 4: Construir y subir la imagen de Angular
    - name: Build and push Angular image
      working-directory: /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work/training-devops-selfhosted/training-devops-selfhosted/training-angular
      run: |
        docker build -t ismaelmrn/training-angular:0.0.1 .
        docker push ismaelmrn/training-angular:0.0.1

    # Paso 5: Construir y subir la imagen de Spring Boot
    - name: Build and push Spring Boot image
      working-directory: /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work/training-devops-selfhosted/training-devops-selfhosted/training-spring-boot
      run: |
        mvn clean package
        docker build -t ismaelmrn/training-spring-boot:0.0.1 .
        docker push ismaelmrn/training-spring-boot:0.0.1