name: CI - Build and Push Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: repo #Evitar crear un subdirectorio adicional

    # Paso 2: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Paso 3: Construir y subir la imagen de Angular
    - name: Build and push Angular image
      working-directory: /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work/training-devops-selfhosted/training-devops-selfhosted/repo/training-angular
      run: |
        docker build -t ismaelmrn/training-angular:0.0.1 .
        docker push ismaelmrn/training-angular:0.0.1

    # Paso 4: Construir y subir la imagen de Spring Boot
    - name: Build and push Spring Boot image
      working-directory: /mnt/c/Users/jose.i.marin.ghalem/actions-runner/_work/training-devops-selfhosted/training-devops-selfhosted/repo/training-spring-boot
      run: |
        mvn clean package
        docker build -t ismaelmrn/training-spring-boot:0.0.1 .
        docker push ismaelmrn/training-spring-boot:0.0.1