name: CI - Build and Push Images
#
# Este flujo de trabajo se encarga de construir y subir imágenes de Docker para Angular y Spring Boot,
# así como configurar Rancher-desktop.

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted


    steps:

    - name: pwd
      run: pwd 
      
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    
      
    # Paso Intermedio: Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    # Paso 3: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Paso 4: Construir y subir la imagen de Angular
    - name: Build and push Angular image
      working-directory: ${{ github.workspace }}/training-angular/helloworld1
      run: |
        docker build -t ismaelmrn/training-angular:0.0.1 .
        docker push ismaelmrn/training-angular:0.0.1

    # Paso 5: Construir y subir la imagen de Spring Boot
    - name: Build and push Spring Boot image
      working-directory: ${{ github.workspace }}/training-spring-boot/helloworld
      run: |
        mvn clean package
        docker build -t ismaelmrn/training-spring-boot:0.0.1 .
        docker push ismaelmrn/training-spring-boot:0.0.1

    # Paso 6: Configurar kubectl & rancher-desktop
    - name: Configure kubeconfig
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p ~/.kube
        cp ~/../../.kube/config ~/.kube/config
        kubectl config use-context rancher-desktop
        kubectl config current-context
        kubectl cluster-info